analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3274099,"name"\:"First Project","teamId"\:3245941,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3311534,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3245941,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.hub.switchHub.enable=true
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
