<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_imgLogin_1</name>
   <tag></tag>
   <elementGuidId>18c61d8f-50b7-491f-aebc-66073e587f85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#imgLogin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'imgLogin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Submit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>434eca67-336e-4e4d-881e-3049c48aa549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>c226fe9c-3b1e-4714-a7df-f170393d9f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>imgLogin</value>
      <webElementGuid>5a01d721-a129-42a8-addf-ff5b990cc390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>imgLogin</value>
      <webElementGuid>282fbe58-6059-4b31-bdc7-0d2d5dd6c1a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/btn_login.jpg</value>
      <webElementGuid>7c48ea96-a75e-41ce-9dcd-3578097169d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return Validate();</value>
      <webElementGuid>2881db0c-a721-4ee4-8338-288fbca48dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a087cc1fd77f9eea4157cd5d2c0736c2</value>
      <webElementGuid>b2415e9f-7e4c-4bbb-8a18-e036875b98fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'imgLogin']</value>
      <webElementGuid>87801c19-1781-400e-ae77-958ef1b6214b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'imgLogin']</value>
      <webElementGuid>51d5c60e-7979-49e2-bc49-1f13f93372ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'image' and @name = 'imgLogin' and @id = 'imgLogin' and @src = 'images/btn_login.jpg']</value>
      <webElementGuid>d5cb011d-06c0-473d-83ef-9f37d6a4ec0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
