<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00_ContentPlaceHolder1_txtAreaName</name>
   <tag></tag>
   <elementGuidId>cb76ef8d-c45a-4cae-89a4-792fec0553e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;ctl00\$ContentPlaceHolder1\$txtAreaName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'ctl00$ContentPlaceHolder1$txtAreaName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ctl00_ContentPlaceHolder1_txtAreaName</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa83f8ba-7bd5-4e17-9b50-6ba5e9e99629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentPlaceHolder1$txtAreaName</value>
      <webElementGuid>7f4d1e2c-2945-4078-a4de-28cddfa6ef5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f50820c8-136a-4bea-9236-2957a6b73676</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>d349ef78-5bb6-4d8e-9e57-6baed48a62f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ContentPlaceHolder1_txtAreaName</value>
      <webElementGuid>c294ef42-f9e1-46fa-81b9-234185ff3a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box</value>
      <webElementGuid>b6c611e2-2bdc-421b-a346-7dd5c403d058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return characterWithSpaceAndBracket(event)</value>
      <webElementGuid>598c9257-b400-4d1a-a8ca-6c172fd674d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-dc17c149f6ab21269a0b8c98cbf6541c</value>
      <webElementGuid>c62166a2-c474-4782-bc62-fe5cc242a5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'ctl00$ContentPlaceHolder1$txtAreaName']</value>
      <webElementGuid>5e6fc81e-3e60-4492-9d26-90a3eb417d6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'ctl00$ContentPlaceHolder1$txtAreaName']</value>
      <webElementGuid>5c98530b-e881-4bf8-8d35-6bad66981360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$ContentPlaceHolder1$txtAreaName' and @type = 'text' and @id = 'ctl00_ContentPlaceHolder1_txtAreaName']</value>
      <webElementGuid>d7c5071e-17f3-4634-86fb-9b24154dddde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
